[phases.setup]
nixPkgs = ["ffmpeg", "chromium"]

[phases.install]
cmds = ["npm ci", "npx playwright install chromium --with-deps"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start -- -p $PORT"